### ISSUE TITLE
Kheops UI shows error when uploading a folder containing .dcm files

### ISSUE THREAD

**Issue by RajaMuneerBaigal** [OsiriX-Foundation/kheops#63]
Hi Greetings,
I tried to locally install the kheops as well as on the prod server following the documentation provided here on this URL:
[](https://docs.kheops.online/docs/installation)

I tried downloading the versions v1.1.1, v1.1 and v1.0.8. In all of them I am facing a same issue which is in kheops UI when I try to upload the whole folder containing dcmchi images. For some folders it works and for others it is showing me errors  which you can see from the images below.
please do let me know if I am missing out on anything or is this the issue in the code because when I tried version 0.9.5 it works fine in that version.

Here is my docker-compose.yml:
`
services:
# In a production environment, Keycloak should be set up separately from KHEOPS.
# KHEOPS interacts with Keycloak using the Authorization Code flow please
# refer to the Keycloak documentation for instruction on how to properly
# secure Keycloak.
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    container_name: keycloak
    command: ["-b", "0.0.0.0"]
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD_FILE: /run/secrets/keycloak_admin_password
      KEYCLOAK_IMPORT: /tmp/kheops-realm.json
# In this configuration, users of the Web UI will access KHEOPS and be
# redirected to Keycloak using the frontend URL 
      KEYCLOAK_FRONTEND_URL: http://127.0.0.1:8080/auth
    volumes:
      - keycloak-standalone-data:/opt/jboss/keycloak/standalone/data
      - ./realm/kheops-realm.json:/tmp/kheops-realm.json:cached
      - ./themes/kheops:/opt/jboss/keycloak/themes/kheops:cached
    secrets:
      - keycloak_admin_password
    networks:
      - keycloak_network

# DCM4CHEE uses the an LDAP server for configuration, as per the DICOM 
# Application Configuration Management Profile. For this installation
# we do not apply any custom configuration to DCM4CEE
  ldap:
    container_name: ldap
    image: dcm4che/slapd-dcm4chee:2.6.0-25.1
    env_file: docker-compose.env
    networks:
      - pacs_network

# DCM4CHEE uses this PostgreSQL database
  pacs-postgres:
    container_name: pacspostgres
    image: dcm4che/postgres-dcm4chee:13.5-25
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      POSTGRES_DB: kheops_pacs
      POSTGRES_USER: kheops_pacs
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_pacsdb_pass
    env_file: docker-compose.env
    volumes:
      - dcm4chee-db-data:/var/lib/postgresql/data
    secrets:
      - kheops_pacsdb_pass
    networks:
      - pacs_network

# The main DCM4CHEE container
  pacs-arc:
    container_name: pacsarc
    image: dcm4che/dcm4chee-arc-psql:5.25.1
    env_file: docker-compose.env
    environment:
      POSTGRES_DB: kheops_pacs
      POSTGRES_USER: kheops_pacs
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_pacsdb_pass
      STORAGE_DIR: /storage/fs1
      POSTGRES_HOST: pacspostgres
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 pacspostgres:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
    secrets:
      - kheops_pacsdb_pass
    depends_on:
      - ldap
      - pacs-postgres
    volumes:
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - dcm4chee-arc-storage:/storage
    networks:
      - pacs_network

# KHEOPS persists all data to this PostgreSQL database
  kheops-postgres:
    container_name: kheopspostgres
    image: postgres:12.9-alpine
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kheops
      POSTGRES_USER: kheopsuser
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_authdb_pass
    secrets:
      - kheops_authdb_pass
    networks:
      - kheops_network

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:v1.0.8
    env_file: docker-compose.env
    environment:
      KHEOPS_OIDC_PROVIDER: http://keycloak:8080/auth/realms/kheops
      CATALINA_OPTS: -Duser.timezone=UTC
    depends_on:
      - kheops-postgres
    secrets:
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_auth_admin_password
    networks:
      - kheops_network
      - keycloak_network
  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:v1.0.8
    env_file: docker-compose.env
    secrets:
      - kheops_client_zippersecret
    networks:
      - kheops_network

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:v1.0.8
    env_file: docker-compose.env
    networks:
      - frontend_network

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:v1.0.8
    env_file: docker-compose.env
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    networks:
      - kheops_network

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:v1.0.8-insecure
    container_name: kheopsreverseproxy
    env_file: docker-compose.env
    ports:
      - "80:8042"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - kheops-ui
      - kheops-zipper
    networks:
      - kheops_network
      - frontend_network

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:v1.0.8
    depends_on:
      - pacs-arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    networks:
      - pacs_network
      - kheops_network

#####################################################################
#####################################################################

secrets:
  keycloak_admin_password:
    file: secrets/keycloak_admin_password
  kheops_authdb_pass:
    file: secrets/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: secrets/kheops_pacsdb_pass
  kheops_auth_hmasecret:
    file: secrets/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: secrets/kheops_auth_hmasecret_post
  kheops_client_dicomwebproxysecret:
    file: secrets/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: secrets/kheops_client_zippersecret
  kheops_auth_admin_password:
    file: secrets/kheops_auth_admin_password

volumes:
  keycloak-standalone-data:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  dcm4chee-arc-storage:
  kheops-db-data:

networks:
# Network used for communication between the backend KHEOPS components
  kheops_network:
    driver: bridge
# The PACS network isolates the PACS from the reset of KHEOPS ensuring that
# all communication between KHEOPS and the PACS goes the the authorization
# proxy.
  pacs_network:
    driver: bridge
# Network reserved for communication with the frontend UI.
  frontend_network:
    driver: bridge
# Network for the backend communication between the KHEOPS Authorization
# Server and Keycloak.
  keycloak_network:
    driver: bridge

`

The docker-compose.env is same as default as I am testing this on local. 
![Screenshot from 2024-04-25 17-59-23](https://github.com/OsiriX-Foundation/kheops/assets/105891199/07b3f73a-11ea-4b64-967c-1a64a8e616db)
![image](https://github.com/OsiriX-Foundation/kheops/assets/105891199/bf5f93b1-b853-413d-8413-0ad48297403f)

![image](https://github.com/OsiriX-Foundation/kheops/assets/105891199/147f58d2-aded-49f1-b90f-ea98572536c7)

![image](https://github.com/OsiriX-Foundation/kheops/assets/105891199/818ff582-bc0d-46a3-a4d3-a43a66a6d41f)

**Comment by RajaMuneerBaigal** [comment]
@spalte Thank you for the response but where do I need to set it in which file. In docker-compose.env or in any service in docker-compose file as environment variable?

**Comment by RajaMuneerBaigal** [comment]
I did add the environmnet variable to the docker-compose.env file but still the same issue.
`
kheopsdicomwebproxy     | 05-May-2024 02:16:36.951 WARNING [http-nio-8080-exec-5] online.kheops.proxy.stow.authorization.AuthorizationManager.getAuthorization Instances verification rejected for series:StudyInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.4 SeriesInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.106
kheopsdicomwebproxy     | 05-May-2024 02:16:36.953 WARNING [http-nio-8080-exec-5] online.kheops.proxy.stow.Proxy.processPart Unable to get authorization for part:4, Part InstanceIDs:StudyInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.4 SeriesInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.106 SOPInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.170 SOPClassUID:1.2.840.10008.5.1.4.1.1.2,
kheopsdicomwebproxy     | 	Reason:SERIES_ACCESS_FORBIDDEN
kheopsdicomwebproxy     | online.kheops.proxy.stow.authorization.AuthorizationManagerException
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.authorization.AuthorizationManager.getAuthorization(AuthorizationManager.java:103)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.Proxy.processPart(Proxy.java:71)
kheopsdicomwebproxy     | 		at org.dcm4che3.mime.MultipartParser.parse(MultipartParser.java:76)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.Proxy.processStream(Proxy.java:56)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.resource.Resource.lambda$processProxy$0(Resource.java:186)
kheopsdicomwebproxy     | 		at online.kheops.proxy.multipart.MultipartStreamingProvider.writeTo(MultipartStreamingProvider.java:72)
kheopsdicomwebproxy     | 		at online.kheops.proxy.multipart.MultipartStreamingProvider.writeTo(MultipartStreamingProvider.java:19)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:461)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:443)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:367)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:265)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:630)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:665)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:659)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:659)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:629)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:434)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:340)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.resource.Resource.processProxy(Resource.java:200)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.resource.Resource.store(Resource.java:132)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.resource.Resource.stow(Resource.java:95)
kheopsdicomwebproxy     | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
kheopsdicomwebproxy     | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
kheopsdicomwebproxy     | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kheopsdicomwebproxy     | 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kheopsdicomwebproxy     | 		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kheopsdicomwebproxy     | 		at online.kheops.proxy.filter.FixTypeQuoteFilter.doFilter(FixTypeQuoteFilter.java:54)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
kheopsdicomwebproxy     | 		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
kheopsdicomwebproxy     | 		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
kheopsdicomwebproxy     | 		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
kheopsdicomwebproxy     | 		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
kheopsdicomwebproxy     | 		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
kheopsdicomwebproxy     | 		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
kheopsdicomwebproxy     | 		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
kheopsdicomwebproxy     | 		at java.base/java.lang.Thread.run(Thread.java:829)
kheopsauthorization     | 05-May-2024 02:16:36.999 KHEOPS [http-nio-8080-exec-5] online.kheops.auth_server.util.KheopsLogBuilder.log user=5d71d183-28a6-4149-87cb-33b07c4265e5 tokenType=KEYCLOAK_TOKEN link=false action=VERIFY_INSTANCE studyUID=1.2.276.0.50.192168001099.8252157.14547392.4 seriesUID=1.2.276.0.50.192168001099.8252157.14547392.391 isValid=false authorized=true invalidTags=524336 
kheopsdicomwebproxy     | 05-May-2024 02:16:37.004 WARNING [http-nio-8080-exec-5] online.kheops.proxy.stow.authorization.AuthorizationManager.getAuthorization Instances verification rejected for series:StudyInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.4 SeriesInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.391
kheopsdicomwebproxy     | 05-May-2024 02:16:37.005 WARNING [http-nio-8080-exec-5] online.kheops.proxy.stow.Proxy.processPart Unable to get authorization for part:5, Part InstanceIDs:StudyInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.4 SeriesInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.391 SOPInstanceUID:1.2.276.0.50.192168001099.8252157.14547392.428 SOPClassUID:1.2.840.10008.5.1.4.1.1.2,
kheopsdicomwebproxy     | 	Reason:SERIES_ACCESS_FORBIDDEN
kheopsdicomwebproxy     | online.kheops.proxy.stow.authorization.AuthorizationManagerException
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.authorization.AuthorizationManager.getAuthorization(AuthorizationManager.java:103)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.Proxy.processPart(Proxy.java:71)
kheopsdicomwebproxy     | 		at org.dcm4che3.mime.MultipartParser.parse(MultipartParser.java:76)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.Proxy.processStream(Proxy.java:56)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.resource.Resource.lambda$processProxy$0(Resource.java:186)
kheopsdicomwebproxy     | 		at online.kheops.proxy.multipart.MultipartStreamingProvider.writeTo(MultipartStreamingProvider.java:72)
kheopsdicomwebproxy     | 		at online.kheops.proxy.multipart.MultipartStreamingProvider.writeTo(MultipartStreamingProvider.java:19)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:461)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:443)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:367)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:265)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:630)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:665)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:659)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:659)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:629)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:434)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:340)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.resource.Resource.processProxy(Resource.java:200)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.resource.Resource.store(Resource.java:132)
kheopsdicomwebproxy     | 		at online.kheops.proxy.stow.resource.Resource.stow(Resource.java:95)
kheopsdicomwebproxy     | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
kheopsdicomwebproxy     | 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
kheopsdicomwebproxy     | 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kheopsdicomwebproxy     | 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
kheopsdicomwebproxy     | 		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kheopsdicomwebproxy     | 		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kheopsdicomwebproxy     | 		at online.kheops.proxy.filter.FixTypeQuoteFilter.doFilter(FixTypeQuoteFilter.java:54)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
kheopsdicomwebproxy     | 		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
kheopsdicomwebproxy     | 		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
kheopsdicomwebproxy     | 		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
kheopsdicomwebproxy     | 		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
kheopsdicomwebproxy     | 		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
kheopsdicomwebproxy     | 		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
kheopsdicomwebproxy     | 		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
kheopsdicomwebproxy     | 		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
kheopsdicomwebproxy     | 		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
kheopsdicomwebproxy     | 		at java.base/java.lang.Thread.run(Thread.java:829)
kheopsauthorization     | 05-May-2024 02:16:37.059 KHEOPS [http-nio-8080-exec-7] online.kheops.auth_server.util.KheopsLogBuilder.log user=5d71d183-28a6-4149-87cb-33b07c4265e5 tokenType=KEYCLOAK_TOKEN link=false sourceIP=172.30.0.1 action=INBOX_INFO 
kheopsauthorization     | 05-May-2024 02:16:37.082 KHEOPS [http-nio-8080-exec-9] online.kheops.auth_server.util.KheopsLogBuilder.log user=5d71d183-28a6-4149-87cb-33b07c4265e5 tokenType=KEYCLOAK_TOKEN link=false sourceIP=172.30.0.1 action=QIDO_STUDIES album=inbox 
kheopsauthorization     | 05-May-2024 02:16:37.136 KHEOPS [http-nio-8080-exec-10] online.kheops.auth_server.util.KheopsLogBuilder.log user=5d71d183-28a6-4149-87cb-33b07c4265e5 tokenType=KEYCLOAK_TOKEN link=false sourceIP=172.30.0.1 action=QIDO_SERIES studyUID=1.2.276.0.50.192168001099.8252157.14547392.4 seriesUID=1.2.276.0.50.192168001099.8252157.14547392.391 album=inbox 
`

**Comment by RajaMuneerBaigal** [comment]
Thank you it works perfectly now.
